import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";

import Header from "./components/layout/Header";
import Footer from "./components/layout/Footer";
import Providers from "./components/providers/SessionProvider";
import { NotificationProvider } from "./components/providers/NotificationProvider";

const inter = Inter({
  subsets: ["latin"],
  variable: "--font-inter",
  weight: ["400", "500", "600", "700"],
});

export const metadata: Metadata = {
  title: "E-Commerce Project",
  description: "Generated by create next app",
};

export const viewport = {
  width: "device-width",
  initialScale: 1.0,
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className={inter.variable}>
      <body className="antialiased font-sans min-h-screen flex flex-col">
        <Providers>
          <NotificationProvider>
            <Header />
            <main className="flex-1 mb-20 mt-10 lg:mx-10">{children}</main>
            <Footer />
          </NotificationProvider>
        </Providers>
      </body>
    </html>
  );
}
